#!/bin/bash

set -euxo pipefail

PORT=${2:-5000}
NAME=registry

case $1 in
    u|up|start)
        # Add to /etc/docker/daemon.json:
        #    {
        #      "insecure-registries" : ["localhost:${PORT}"]
        #    }
        docker run -d -p ${PORT}:5000 --restart=always --name ${NAME} registry:2
        ;;
    d|down|stop)
        docker stop ${NAME} && docker rm -v ${NAME}
        ;;
    st|status|*)
        curl http://localhost:${PORT}/v2/_catalog | json_pp
        ;;
esac
