#!/bin/bash

set -euxo pipefail

# External interface
IFACE=eth0

# Drop firewall settings
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X

# Allow already established connections. FIRST RULE IN THE CHAIN!!!
iptables -A INPUT -i ${IFACE} -m state --state ESTABLISHED,RELATED -j ACCEPT
# Allow SSH connections
iptables -A INPUT -i ${IFACE} -p tcp --dport 22 -j ACCEPT
# Allow WireGuard connections
iptables -A INPUT -i ${IFACE} -p udp --dport 34567 -j ACCEPT
# Drop other incoming connections. LAST RULE IN THE CHAIN!!!
iptables -A INPUT -i ${IFACE} -j DROP

# Allow already established transitional connections
iptables -A FORWARD -i ${IFACE} -o wg0 -m state --state ESTABLISHED,RELATED -j ACCEPT
# Drop incoming transitional traffic
iptables -A FORWARD -i ${IFACE} -o wg0 -j DROP

# Enable MASQUERADE for WireGuard clients
iptables -t nat -A POSTROUTING -o ${IFACE} -s 10.20.0.0/24 -j MASQUERADE

# Enable IP forwarding
sysctl net.ipv4.ip_forward=1
